### ISSUE TITLE
Crash when parsing valid JUnit files

### ISSUE THREAD

**Issue by KrauseFx** [orta/danger-junit#3]
Seems like this plugin doesn't support all kinds of JUnit files yet

TestFile.xml

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="1">
    <testsuite name="ThemojiUITests" tests="2" failures="1">
        <testcase classname="ThemojiUITests" name="testExample()">
        </testcase>
        <testcase classname="ThemojiUITests" name="testIsBroken()">
            <failure message="XCTAssertTrue failed - /Users/fkrause/Developer/themoji/ThemojiUITests/ThemojiUITests.swift:24">
            </failure>
        </testcase>
    </testsuite>
</testsuites>
```

``` ruby
=> [#<Ox::Element:0x007ffed5b24928 @attributes={:classname=>"ThemojiUITests", :name=>"testExample()"}, @nodes=["\n        "], @value="testcase">,
 #<Ox::Element:0x007ffed5b24798
  @attributes={:classname=>"ThemojiUITests", :name=>"testIsBroken()"},
  @nodes=
   [#<Ox::Element:0x007ffed5b246a8
     @attributes={:message=>"XCTAssertTrue failed - /Users/fkrause/Developer/themoji/ThemojiUITests/ThemojiUITests.swift:24"},
     @nodes=["\n            "],
     @value="failure">],
  @value="testcase">]
[5] pry(#<Danger::DangerJunit>)> failed_tests.select { |test| test.nodes.count > 0 }
=> [#<Ox::Element:0x007ffed5b24928 @attributes={:classname=>"ThemojiUITests", :name=>"testExample()"}, @nodes=["\n        "], @value="testcase">,
 #<Ox::Element:0x007ffed5b24798
  @attributes={:classname=>"ThemojiUITests", :name=>"testIsBroken()"},
  @nodes=
   [#<Ox::Element:0x007ffed5b246a8
     @attributes={:message=>"XCTAssertTrue failed - /Users/fkrause/Developer/themoji/ThemojiUITests/ThemojiUITests.swift:24"},
     @nodes=["\n            "],
     @value="failure">],
  @value="testcase">]
```

Stack Trace

```
[!] Invalid `Dangerfile` file: undefined method `value' for "\n        ":String. Updating the Danger gem might fix the issue.

 #  from Dangerfile:4
 #  -------------------------------------------
 #    puts "Parsing JUnit file at path '#{path}'"
 >    junit.parse(path)
 #    junit.report
 #  -------------------------------------------

  /Users/fkrause/Developer/hacking/danger-junit/lib/junit/plugin.rb:100:in `block in parse'
  /Users/fkrause/Developer/hacking/danger-junit/lib/junit/plugin.rb:100:in `select'
  /Users/fkrause/Developer/hacking/danger-junit/lib/junit/plugin.rb:100:in `parse'
  Dangerfile:4:in `block (2 levels) in parse'
  Dangerfile:2:in `each'
  Dangerfile:2:in `block in parse'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/lib/danger/danger_core/dangerfile.rb:193:in `eval'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/lib/danger/danger_core/dangerfile.rb:193:in `block in parse'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/lib/danger/danger_core/dangerfile.rb:189:in `instance_eval'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/lib/danger/danger_core/dangerfile.rb:189:in `parse'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/lib/danger/commands/local.rb:109:in `run'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/danger-a67bc71710d9/bin/danger:5:in `<top (required)>'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bin/danger:22:in `load'
  /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bin/danger:22:in `<top (required)>'
```

Before working on a fix I'd just like to know if I'm missing something, or if I misunderstood how the JUnit format works.

**Comment by orta** [comment]
Yeah the JUnit spec is just what everyone makes up, this would make a great a test case 👍  - which is how I've been writing them so far, got one from Rspec, xcpretty and one from someone else test suite

**Comment by KrauseFx** [comment]
Working on this right now. I can't assign the issue to myself, can you grant me commit access @ota? 👍

**Comment by orta** [comment]
Done 👍 - and released the build
